services:
  - type: web
    name: business-news-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m waitress.server app:app"
    envVars:
      - key: FLASK_APP
        value: "app.py"


